name: benchmark

on:
  push:
    branches:
      - "master"

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go.
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.6

      - name: Check out code into the Go module directory.
        uses: actions/checkout@v2

      - name: Give me just shared dir lol GitHub Action!
        run: mkdir /tmp/cache

      - uses: actions/cache@v1
        with:
          path: /tmp/cache
          key: benchmark-results

      - name: Run all benchmarks and compare with newest release.
        run: make bench-master
